function articleLoad(id) {
  if (id = "btn1") {
    document.getElementById("articleHead").innerHTML = "How reading changes your perspective";
    document.getElementById("articleBody").innerHTML = "Reading Books Improves Imagination<br/>Books are one of the most creative art forms. Every book that we read opens up a world of Sed tincidunt felis lobortis ligula lobortis, id molestie leo varius. Integer accumsan enim et ante tristique, gravida condimentum mi porta. Vivamus sed auctor dolor, in vulputate elit. Nulla ac venenatis nibh. Vestibulum auctor iaculis elit. Cras pulvinar, magna sit amet fermentum lobortis, mauris odio suscipit ex, et luctus felis eros nec justo. Vestibulum at mi sed nulla pellentesque ultricies. Quisque eu elementum neque. In hac habitasse platea dictumst. Donec at tristique elit. Nam in tempor velit. Nunc sagittis malesuada ultrices. Suspendisse potenti.<br/>Ut ornare ligula et neque eleifend luctus. Proin venenatis sapien ante, vitae tempor odio finibus id. Cras quis aliquet orci. In eros massa, porta eget malesuada in, tempus nec lacus. Nunc congue rhoncus velit sed venenatis. Fusce vitae ante vitae ligula interdum sodales. Curabitur convallis sem id tortor mattis hendrerit. Integer in scelerisque eros. Morbi blandit odio ac sapien tristique fermentum. Phasellus eget auctor nibh. Sed finibus tincidunt pulvinar. Ut nisl justo, ultrices non varius eget, placerat quis arcu.<br/>Aenean vestibulum arcu et sollicitudin aliquam. Praesent dui nisi, scelerisque sit amet euismod quis, euismod id leo. Aliquam erat volutpat. Morbi condimentum turpis justo, ut euismod odio maximus sed. Nam eleifend nisi sed tortor congue commodo. Ut tempus tristique lacus, sagittis mattis dolor commodo ac. In tempus tortor in aliquet tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean dignissim diam sed dolor tincidunt, id venenatis lacus tempor. Pellentesque gravida auctor porta. Maecenas mollis tristique neque in hendrerit. Donec eget cursus lacus, et euismod metus. Curabitur imperdiet nisi quam, nec consectetur nunc molestie eget. Quisque vitae lacus ut dui finibus condimentum et eget turpis. Nulla eget lectus a purus fermentum viverra eu at mi. Pellentesque dignissim massa metus, ut aliquam eros luctus at.";
  } else if (id = "btn2") {
    document.getElementById("articleHead").innerHTML = "The art of writing";
    document.getElementById("articleBody").innerHTML = "Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading.  Vivamus ut nulla tristique, convallis risus sit amet, maximus ipsum. Nullam ultricies bibendum tellus vitae consectetur. Nulla facilisi. Fusce at rutrum est. Phasellus fermentum eu diam elementum ullamcorper. Donec aliquet dolor massa. Mauris at lacus neque.<br/>Donec venenatis lorem sed viverra blandit. Nullam lobortis sapien ut congue sollicitudin. Nunc vestibulum metus vel sem interdum, sed congue nisl blandit. Praesent ac nisi justo. In scelerisque ante at ornare pharetra. Aliquam euismod turpis vel auctor vestibulum. Etiam ex sapien, ultricies vel quam vel, mollis facilisis est. Cras lobortis laoreet orci, vitae ultrices est pretium vitae. Suspendisse ut convallis dolor. Pellentesque vitae odio ac urna pulvinar placerat. Cras accumsan augue leo, eu maximus massa sollicitudin at. Sed ac dolor ut est ultrices luctus. Nunc rutrum accumsan libero et interdum. Maecenas nec fermentum tortor, tempus pulvinar nisi. Nulla porta sem facilisis hendrerit consequat. Quisque et eleifend mi.<br/>Suspendisse a erat ante. Suspendisse id odio sit amet orci porta pharetra. Pellentesque vel diam suscipit ligula egestas vulputate. Nam imperdiet elementum nisl, sed eleifend quam sagittis in. Fusce viverra, nisl at luctus ullamcorper, libero purus malesuada ex, eu vehicula nunc urna malesuada ante. Suspendisse accumsan ante mi, ut venenatis eros volutpat non. Nunc feugiat nec magna ac rhoncus. Nulla aliquet nisi sit amet nibh ultrices pulvinar. Phasellus pulvinar mi lectus, quis consectetur massa egestas a. Nunc scelerisque, dolor ac iaculis vestibulum, nulla nisl cursus libero, sit amet blandit sem eros in mauris. Sed id neque imperdiet, accumsan felis eu, vehicula felis. ";
  } else if (id = "btn3") {
    document.getElementById("articleHead").innerHTML = "My new digital reading habits";
    document.getElementById("articleBody").innerHTML = "Welcome to your blog post. Use this space to connect with your readers and potential customers in a way that’s current and interesting. Think of it as an ongoing conversation where you can share updates about business, trends, news, and more";
  } else if (id = "btn4") {
    document.getElementById("articleHead").innerHTML = "The Best Vacation Books You Will Ever Read";
    document.getElementById("articleBody").innerHTML = "";
  } else if (id = "btn5") {
    document.getElementById("articleHead").innerHTML = "Favorite Audiobooks";
    document.getElementById("articleBody").innerHTML = "";
  }
}